name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: c7c8d7bcbc8f12f27e740fa41755d9dcb4e2147c
        
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
  
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.6
      
    - name: Overwrite old pom.xml
      run: |
        curl -o new_pom.xml https://pastebin.com/raw/mRNeKXdN
        mv new_pom.xml pom.xml

    - name: Build project with JDK 17
      run: mvn test

    - name: Upload JaCoCo reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report-${{ github.event.repository.name }}
        path: '**/target/site/jacoco/**/*.html'
