name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: c7c8d7bcbc8f12f27e740fa41755d9dcb4e2147c
        
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven 3.9.6
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
          wget -q -O /tmp/apache-maven-3.9.6-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          sudo tar xf /tmp/apache-maven-3.9.6-bin.tar.gz -C /opt
          sudo ln -sfn /opt/apache-maven-3.9.6 /usr/share/apache-maven
          sudo ln -sfn /opt/apache-maven-3.9.6 /usr/share/maven
          echo "export M2_HOME=/usr/share/maven" >> ~/.bashrc
          echo "export MAVEN_HOME=/usr/share/maven" >> ~/.bashrc
          echo "export PATH=\${M2_HOME}/bin:\${PATH}" >> ~/.bashrc
          source ~/.bashrc
          mvn --version
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew update
          brew install maven
        fi
        mvn --version
      
    - name: Overwrite old pom.xml
      run: |
        curl -o new_pom.xml https://pastebin.com/raw/mRNeKXdN
        mv new_pom.xml pom.xml

    - name: Build project with JDK 17
      run: mvn test

    - name: Upload JaCoCo reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report-${{ github.event.repository.name }}
        path: '**/target/site/jacoco/**/*.html'
